# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.snowballfinance.com/ios/cocoapodsspecs.git'


# ignore all warnings from all pods
inhibit_all_warnings!
use_modular_headers!


target 'Demo' do
    pod 'RefreshController', :path => '../'
end